'use strict';
// @must-b/pack-channels — auto-generated by scripts/build-packs.mjs
// Extensions: telegram, whatsapp, discord, slack, signal, imessage, matrix, msteams, line, feishu, googlechat, irc, nostr, twitch, zalouser, bluebubbles, mattermost, synology-chat, nextcloud-talk, tlon

try { require('./extensions/telegram/index.cjs'); } catch(e) { console.warn('[pack-channels] telegram load error:', e.message); }
try { require('./extensions/whatsapp/index.cjs'); } catch(e) { console.warn('[pack-channels] whatsapp load error:', e.message); }
try { require('./extensions/discord/index.cjs'); } catch(e) { console.warn('[pack-channels] discord load error:', e.message); }
try { require('./extensions/slack/index.cjs'); } catch(e) { console.warn('[pack-channels] slack load error:', e.message); }
try { require('./extensions/signal/index.cjs'); } catch(e) { console.warn('[pack-channels] signal load error:', e.message); }
try { require('./extensions/imessage/index.cjs'); } catch(e) { console.warn('[pack-channels] imessage load error:', e.message); }
try { require('./extensions/matrix/index.cjs'); } catch(e) { console.warn('[pack-channels] matrix load error:', e.message); }
try { require('./extensions/msteams/index.cjs'); } catch(e) { console.warn('[pack-channels] msteams load error:', e.message); }
try { require('./extensions/line/index.cjs'); } catch(e) { console.warn('[pack-channels] line load error:', e.message); }
try { require('./extensions/feishu/index.cjs'); } catch(e) { console.warn('[pack-channels] feishu load error:', e.message); }
try { require('./extensions/googlechat/index.cjs'); } catch(e) { console.warn('[pack-channels] googlechat load error:', e.message); }
try { require('./extensions/irc/index.cjs'); } catch(e) { console.warn('[pack-channels] irc load error:', e.message); }
try { require('./extensions/nostr/index.cjs'); } catch(e) { console.warn('[pack-channels] nostr load error:', e.message); }
try { require('./extensions/twitch/index.cjs'); } catch(e) { console.warn('[pack-channels] twitch load error:', e.message); }
try { require('./extensions/zalouser/index.cjs'); } catch(e) { console.warn('[pack-channels] zalouser load error:', e.message); }
try { require('./extensions/bluebubbles/index.cjs'); } catch(e) { console.warn('[pack-channels] bluebubbles load error:', e.message); }
try { require('./extensions/mattermost/index.cjs'); } catch(e) { console.warn('[pack-channels] mattermost load error:', e.message); }
try { require('./extensions/synology-chat/index.cjs'); } catch(e) { console.warn('[pack-channels] synology-chat load error:', e.message); }
try { require('./extensions/nextcloud-talk/index.cjs'); } catch(e) { console.warn('[pack-channels] nextcloud-talk load error:', e.message); }
try { require('./extensions/tlon/index.cjs'); } catch(e) { console.warn('[pack-channels] tlon load error:', e.message); }

module.exports = { packName: 'channels', extensions: ["telegram","whatsapp","discord","slack","signal","imessage","matrix","msteams","line","feishu","googlechat","irc","nostr","twitch","zalouser","bluebubbles","mattermost","synology-chat","nextcloud-talk","tlon"] };